### ISSUE TITLE
你好，每次上传分片的时候，把md5也带上吧，加个开关

### ISSUE THREAD

**Issue by adacnvwp** [moyuderen/uploader#7]
RT

**Comment by moyuderen** [comment]
增加了hasChunkHash参数，为true时每个chunk会携带用spark-md5生成的hash值

**Comment by adacnvwp** [comment]
这个库会一直更新吗？有计划吗

**Comment by adacnvwp** [comment]
https://github.com/devin87/web-uploader  可以参考下这个库，我之前准备改这个到esm，但是发现了你的这个

**Comment by moyuderen** [comment]
> 这个库会一直更新吗？有计划吗

有时间会保持更新和bugfix

**Comment by moyuderen** [comment]
> https://github.com/devin87/web-uploader 可以参考下这个库，我之前准备改这个到esm，但是发现了你的这个

好的，我学习一下

**Comment by moyuderen** [comment]
> 这个库会一直更新吗？有计划吗

现在仍然起步阶段 有问题欢迎提出
